export default {
  ALL_RESOURCES: 'ALL_RESOURCES',
  BREAK_ROOM: 'BREAK_ROOM',
  GETTING_STARTED: 'GETTING_STARTED',
  LIVE_EVENT: 'LIVE_EVENT',
  PROGRAM_SUPPORT: 'PROGRAM_SUPPORT',
  // might need update
  SHAREABLES: 'SHAREABLES'
};