import keyMirror from '@hmhco/react-utils/src/keyMirror';
export var PAGE_ACTIONS = keyMirror({
  LOAD_TAB_COUNTS: null,
  LOAD_TAB_COUNT: null,
  INVALIDATE_TAB_COUNTS: null,
  FETCH_ASSIGNMENTS: null,
  FETCH_ASSIGNMENTS_ERROR: null,
  LOAD_ASSIGNMENTS: null,
  SUBMIT_ASSIGNMENT: null,
  LAUNCH_ASSIGNMENT: null,
  UPDATE_ASSIGNMENT_STATUS: null,
  SHOW_DIRECTIONS: null,
  HIDE_DIRECTIONS: null,
  LAUNCH_ASSIGNMENT_FROM_DIRECTIONS: null,
  SHOW_FEEDBACK: null,
  CLOSE_FEEDBACK: null,
  REMOVE_ASSIGNMENT: null,
  COMPARE_URL: null,
  SHOW_NOT_AVAILABLE_INSTRUCTION: null,
  HIDE_NOT_AVAILABLE_INSTRUCTION: null,
  SHOW_PARTNER_ASSIGNMENT_MODAL: null,
  HIDE_PARTNER_ASSIGNMENT_MODAL: null,
  SET_ASSIGNMENT_PARTNER: null
});
export var QUERY_STATE_ACTIONS = keyMirror({
  LOAD_TABLE_STATE: null,
  UPDATE_SORT: null,
  UPDATE_PAGE: null,
  SET_OFFSET: null,
  SET_SORT: null,
  SET_SORT_DIRECTION: null,
  SET_CURRENT_PAGE: null,
  SET_CURRENT_TAB: null
});
export var DISCIPLINE_ACTIONS = keyMirror({
  FETCH_DISCIPLINES: null,
  FETCH_DISCIPLINES_ERROR: null,
  LOAD_DISCIPLINES: null,
  SET_DISCIPLINE: null
});